### ISSUE TITLE
Why the program becomes slower and then stops when run at the eval() function? 

### ISSUE THREAD

**Issue by gd2016229035** [chenyuntc/simple-faster-rcnn-pytorch#10]
It is normally in "train" mode ,but becomes slower and slower after about 3500 images had been tested. Finally the process is killed and crashed. Maybe it is because of "memory leak"?
In addition, I modify the line 22 in the code from "20480" to "4096" to avoid error. 
Does anyone have any idea on how I could modify? 
Thank you ~~

**Comment by chenyuntc** [comment]
You'll need more than 16 GB (typically 32GB) to run test. [These lists are memory-consuming](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/blob/master/train.py#L33-L38)

Maybe they can be optimized. 

 You may use `--test-num=1000` to avoid this by reducing test number.

**Comment by gd2016229035** [comment]
Thank you for your reply!~  :)

**Comment by chenyuntc** [comment]
I'll close it for now. Feel free to reopen it if you have any question.
