### ISSUE TITLE
l1_smooth_loss is different with the origin paper

### ISSUE THREAD

**Issue by acgtyrant** [chenyuntc/simple-faster-rcnn-pytorch#11]
I find you use custom computational formula. The origin paper dose not use the custom sigma.

**Comment by chenyuntc** [comment]
The [original papaer Fast R-CNN](https://arxiv.org/abs/1504.08083) use `sigma=1`, that is the same as the `roi_sigma` in [config.py](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/blob/master/utils/config.py#L18).

 RPN in faster rcnn use specified sigma (`rpn_sigma=3`) for rpn anchor loc.

**Comment by acgtyrant** [comment]
Does the original paper use `rpn_sigma=3` too?

**Comment by chenyuntc** [comment]
I can't find any information in the faster rcnn paper. But [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn/blob/96dc9f1dea3087474d6da5a98879072901ee9bf9/models/coco/VGG_CNN_M_1024/faster_rcnn_end2end/train.prototxt#L281) use rpn_sigma=3

**Comment by acgtyrant** [comment]
Thank you for the patient reply.
