### ISSUE TITLE
Classes difference between Faster RCNN and VGG16 ⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄?

### ISSUE THREAD

**Issue by yiran7324** [chenyuntc/simple-faster-rcnn-pytorch#110]
It has always been told that FastRCNN (fc7) outputs a number of classes (20 + 1, VOC 2007), but since vgg is trained on 1000 classes of dataset, the weight (filters) can be slightly different due to num of classes.

Is it reasonable that use this weight to implement FasterRCNN? Or writers of the use the vgg that is also trained on VOC 2007?

**Comment by chenyuntc** [comment]
VGG is trained in ImageNet which has over 1 million images, however, VOC has only 5K trainval set.

The number of classes is not a critical problem, because we mainly use the feature map instead of the directly class id.


Feel Free to reopen it if you have any problems.
