### ISSUE TITLE
Is there any improvement on small object detection?

### ISSUE THREAD

**Issue by changeforan** [chenyuntc/simple-faster-rcnn-pytorch#111]
Hi, @chenyuntc . Thanks for your great work.
I am confused about the peformance on small object ( < 16 pixels width/height) detection. I try to do some improvement on the original Faster R-CNN， like skip-pooling.
But I tried the pretrained vgg16 model. It already has an amazing mAP on my own small object dataset.
So I wonder if you've done some optimization.
Thank you.

**Comment by chenyuntc** [comment]
I didn't try such experiments yet. 
Feel free to reopen it if you have any questions.
