### ISSUE TITLE
model/utils/creator_tool.py, line 259

### ISSUE THREAD

**Issue by lozino** [chenyuntc/simple-faster-rcnn-pytorch#14]
Hi,

can you please explain to me why are you using the following function to compute `gt_argmax_ious`?

`gt_argmax_ious = np.where(ious == gt_max_ious)[0]`

If I understand it correctly, `gt_argmax_ious` should be an array of size K (K is the number of gt boxes) containing the indexes of the rows of `ious` (N x K matrix) corresponding to the maximum values.

Isn't this achieved a couple of lines above?  (`gt_argmax_ious = ious.argmax(axis=0)`) 

To my understanding, `where` is used to return an ordered list of the indexes, but what exactly is the point if said indexes are only used to fill the vector of positive examples ( `label[gt_argmax_ious] = 1`, line 209 ). 

Thank you.

**Comment by chenyuntc** [comment]
This code was bring from [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn/blob/master/lib/rpn/anchor_target_layer.py#L135-L140). In case there are more than one IOUs are the maximum. 

For example ious=[[0.5,0.5,0,0]],   they are two `0.5`, they should  both be labeled as positive anchors.

**Comment by lozino** [comment]
A very fringe case, but indeed one I missed. Now it is clear why.

Thank you!
