### ISSUE TITLE
UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

### ISSUE THREAD

**Issue by chm5174** [chenyuntc/simple-faster-rcnn-pytorch#150]
Hi, I’m having trouble when running the Demo.

I followed the instructions to install the necessary tool and when I run the code on `demo.iqynb`, no images are output on `visdom,` and the following warning appears in pycharm:
```
WARNING:visdom:Without the incoming socket you cannot receive events from the server or register event handlers to your Visdom client.

/opt/conda/conda-bld/pytorch_1565287148058/work/torch/csrc/autograd/python_function.cpp:638: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
```
In addition， The bottom left corner of the Firefox browser visdom window starts with: 
`Loading [MathJax]/extensions/MathZoom.js` , followed by: `File failed to load:/extensions/MathZoom.js`.

However, other visdom samples on Internet can run successfully and display images.

Is it where I am not doing it properly? Could you please help me? Thanks a lot!

**Comment by chm5174** [comment]
By the way, My visdom version is 0.1.8.8

**Comment by liuyl12** [comment]
The same problem...

**Comment by liuyl12** [comment]
> By the way, My visdom version is 0.1.8.8

I fixed the problem by simply chosing the visdom environment to fasterrcnn-caffe. I don't know whether it's suitable for you but you can give it a try.

**Comment by chm5174** [comment]
> > By the way, My visdom version is 0.1.8.8
> 
> I fixed the problem by simply chosing the visdom environment to fasterrcnn-caffe. I don't know whether it's suitable for you but you can give it a try.

The problem is solved because I did not install the correct pytorch version（It must be 0.4x）.

**Comment by luanyunteng** [comment]
I want to know how to solve the problem in the higher pytorch version such as 1.x

**Comment by chensong1995** [comment]
I changed `RoIPooling2D` [here](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/blob/master/model/roi_module.py#L78) to:

```
class RoIPooling2D(t.nn.Module):
    def __init__(self, outh, outw, spatial_scale):
        super(RoIPooling2D, self).__init__()
        self.outh, self.outw, self.spatial_scale = outh, outw, spatial_scale

    def forward(self, x, rois):
        return roi_pool(x, rois, (self.outh, self.outw), self.spatial_scale)
```

I also did `from torchvision.ops import roi_pool` in the same file. This looks to me solve the problem.
