### ISSUE TITLE
VOC数据目录是什么样子的？

### ISSUE THREAD

**Issue by Clannad000000** [chenyuntc/simple-faster-rcnn-pytorch#165]
作者您好，根据您提供的VOC下载链接，解压后数据目录应该是什么样子的呢？而且好像只有val和test的集合，没有train的集合呀

**Comment by Einstellung** [comment]
有的，train和val是一个文件夹，test是一个文件夹

**Comment by HuangTao15521192185** [comment]
> 作者您好，根据您提供的VOC下载链接，解压后数据目录应该是什么样子的呢？而且好像只有val和test的集合，没有train的集合呀
我打不开VOC下载链接，提示连接超时，能否把下载到的VOCtrainval_06-Nov-2007.tar等3个tar包发我呢？
