### ISSUE TITLE
运行结果是什么呢？如何打印mAP呢？

### ISSUE THREAD

**Issue by ZichengDuan** [chenyuntc/simple-faster-rcnn-pytorch#182]
我不想在Visdom里面显示我的结果，我用的是远程服务器，但是我并没有端口映射的权限，本地看不到浏览器的显示结果，请教一下我最后train完了会得到什么东西呢？有点看不太明白，谢谢

**Comment by wutheringcoo** [comment]
老铁，map如何打印呢，搞清楚了？

**Comment by ZichengDuan** [comment]
可以在visdom输出之前把mAP，框选位置，label等信息直接print出来。

**Comment by wutheringcoo** [comment]
可以作者最新的基于pytoch1.0以上版本的源码里面没有关于map的代码，需要自己写吗？

**Comment by ZichengDuan** [comment]
> 可以作者最新的基于pytoch1.0以上版本的源码里面没有关于map的代码，需要自己写吗？

不需要自己写，作者是实现了mAP计算的的。在train.py里有个evaluate，在那里计算了mAP并把数据送到了visdom进行可视化。你在那里把数据截出来就行。

**Comment by wutheringcoo** [comment]
好的，之前在忙别的事，这几天我试试

**Comment by kaizhenzhang** [comment]
我训练完成后visdom的浏览器界面什么都没出现是怎么回事，大家有遇到同样的问题的嘛

**Comment by ZichengDuan** [comment]
> 我训练完成后visdom的浏览器界面什么都没出现是怎么回事，大家有遇到同样的问题的嘛

你好，请参考这篇文章https://blog.csdn.net/chai_zheng/article/details/81545365

**Comment by labhigh** [comment]
> 
> 
> 好的，之前在忙别的事，这几天我试试
@wutheringcoo  have you worked it out? i met the same problem,would you give me some hints? thanks.
