### ISSUE TITLE
visdom server error

### ISSUE THREAD

**Issue by rajeshpaulnadar** [chenyuntc/simple-faster-rcnn-pytorch#203]
Hi,

When I run your code , I am facing an issue from visdom server. is it possible to disable visdom server display . could you please provide a solution for this issue.

![Screenshot from 2020-07-18 14-23-26](https://user-images.githubusercontent.com/39669265/87848936-62078900-c902-11ea-82c8-221aef989630.png)

regards,
Rajesh

**Comment by chenyuntc** [comment]
fixed by https://github.com/chenyuntc/simple-faster-rcnn-pytorch/commit/367db367834efd8a2bc58ee0023b2b628a0e474d
