### ISSUE TITLE
Evaluation score threshold

### ISSUE THREAD

**Issue by lozino** [chenyuntc/simple-faster-rcnn-pytorch#22]
Hi,

is there a specific reason to why `score_threshold` is set to 0.05 when evaluating?

I understand that setting it to 0.7 when visualizing allows to keep only strong positives, but why is such score set so low (0.05) when computing the mAP? Is that value simply derived by dividing 1 by the number of classes (20 in this case)? Should this value be any different when training the network on a different number of classes?

Thank you.

**Comment by chenyuntc** [comment]
This involve how  `mAP` was calculated.

The lower `score_threshold` is, the higher `mAP` May be. But when it cross the boundary, it has no affects anymore. Usually It's save to set `score_threshold` to `0.05` for any condition.

**Comment by chenyuntc** [comment]
I'll close it for now. You may reopen it if you have any question.
