### ISSUE TITLE
NMS  Anaconda3 build failed

### ISSUE THREAD

**Issue by blakeliu** [chenyuntc/simple-faster-rcnn-pytorch#23]
blake@blake-ubuntu:~/cv/object_detection/faster-rcnn/simple-faster-rcnn-pytorch/model/utils/nms$ python build.py build_ext --inplace
running build_ext
cythoning _nms_gpu_post.pyx to _nms_gpu_post.c
building '_nms_gpu_post' extension
creating build
creating build/temp.linux-x86_64-3.5
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -fpic -fPIC -fPIC -I/home/blake/anaconda3/include/python3.5m -c _nms_gpu_post.c -o build/temp.linux-x86_64-3.5/_nms_gpu_post.o
_nms_gpu_post.c:266:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
                               ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by chenyuntc** [comment]
You may refer to #7

**Comment by chenyuntc** [comment]
I'll close it for now. You may reopen it if you have any question.
