### ISSUE TITLE
KeyError: 'unexpected key "classifier.1.weight" in state_dict'

### ISSUE THREAD

**Issue by Usernamezhx** [chenyuntc/simple-faster-rcnn-pytorch#25]
First of all thanks for your code.when i run the command : **python3 train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain**  it will show below. when i search the problew .someone said that the torchvision version should be the 0.1.7. my torchvesion is 0.2.0 . but after installed the torchvision 0.1.8 .it still show me that as the below:
`======user config========
{'caffe_pretrain': True,
 'caffe_pretrain_path': '/root/.torch/models/vgg16-00b39a1b.pth',
 'data': 'voc',
 'debug_file': '/tmp/debugf',
 'env': 'fasterrcnn-caffe',
 'epoch': 14,
 'load_path': None,
 'lr': 0.001,
 'lr_decay': 0.1,
 'max_size': 1000,
 'min_size': 600,
 'num_workers': 8,
 'plot_every': 100,
 'port': 8097,
 'pretrained_model': 'vgg16',
 'roi_sigma': 1.0,
 'rpn_sigma': 3.0,
 'test_num': 10000,
 'test_num_workers': 8,
 'use_adam': False,
 'use_chainer': False,
 'use_drop': False,
 'voc_data_dir': '/data04/data/VOCdevkit/VOC2007/',
 'weight_decay': 0.0005}
==========end============
load data
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    fire.Fire()
  File "/root/anaconda3/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/root/anaconda3/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/root/anaconda3/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 65, in train
    faster_rcnn = FasterRCNNVGG16()
  File "/home/work/zhx/simple-faster-rcnn-pytorch/model/faster_rcnn_vgg16.py", line 62, in __init__
    extractor, classifier = decom_vgg16()
  File "/home/work/zhx/simple-faster-rcnn-pytorch/model/faster_rcnn_vgg16.py", line 16, in decom_vgg16
    model.load_state_dict(t.load(opt.caffe_pretrain_path))
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "classifier.1.weight" in state_dict'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True`

**Comment by chenyuntc** [comment]
Have you  run `python misc/convert_caffe_pretrain.py` before exec this? Something seems to be wrong with the caffe-pretrained file.

**Comment by Usernamezhx** [comment]
thanks for your reply .  I have run the command before :**python misc/convert_caffe_pretrain.py**.and change the path:**caffe_pretrain_path** . I find below in google maybe helpful. I am new pytorch.
https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686

**Comment by chenyuntc** [comment]
Not  `vgg16-00b39a1b.pth`, it should be `vgg16_caffe.pth`

**Comment by Usernamezhx** [comment]
yeah it works . I was confused by the log :**Downloading: "https://s3-us-west-2.amazonaws.com/jcjohns-models/vgg16-00b39a1b.pth" to /root/.torch/models/vgg16-00b39a1b.pth** and then i check your **python misc/convert_caffe_pretrain.py** find that you modify the model vgg16-00b39a1b.pth and then produce the vgg16_caffe.pth. : P

**Comment by Usernamezhx** [comment]
thanks your code let me know how faster rcnn work ! it so cooooooool~

**Comment by riciche** [comment]
I have run the command python misc/convert_caffe_pretrain.py and change vgg16-00b39a1b.pth to vgg16_caffe.pth, but there still a mistake, can you tell me why ,thank you.
======user config========
{'caffe_pretrain': True,
 'caffe_pretrain_path': 'C:\\Users\\superlee\\Desktop\\simple-faster-rcnn-pytorch-master\\vgg16_caffe.pth',
 'data': 'voc',
 'debug_file': '/tmp/debugf',
 'env': 'fasterrcnn-caffe',
 'epoch': 14,
 'load_path': None,
 'lr': 0.001,
 'lr_decay': 0.1,
 'max_size': 1000,
 'min_size': 600,
 'num_workers': 8,
 'plot_every': 100,
 'port': 8097,
 'pretrained_model': 'vgg16',
 'roi_sigma': 1.0,
 'rpn_sigma': 3.0,
 'test_num': 10000,
 'test_num_workers': 8,
 'use_adam': False,
 'use_chainer': False,
 'use_drop': False,
 'voc_data_dir': 'C:\\Users\\superlee\\Desktop\\VOC\\VOCdevkit\\VOC2007',
 'weight_decay': 0.0005}
==========end============
load data
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    fire.Fire()
  File "C:\ProgramData\Anaconda3\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 67, in train
    faster_rcnn = FasterRCNNVGG16()
  File "C:\Users\superlee\Desktop\simple-faster-rcnn-pytorch-master\model\faster_rcnn_vgg16.py", line 63, in __init__
    extractor, classifier = decom_vgg16()
  File "C:\Users\superlee\Desktop\simple-faster-rcnn-pytorch-master\model\faster_rcnn_vgg16.py", line 17, in decom_vgg16
    model.load_state_dict(t.load(opt.caffe_pretrain_path))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VGG:
        Missing key(s) in state_dict: "classifier.0.weight", "classifier.0.bias", "classifier.3.weight", "classifier.3.bias".
        Unexpected key(s) in state_dict: "classifier.1.weight", "classifier.1.bias", "classifier.4.weight", "classifier.4.bias".

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
