### ISSUE TITLE
您好，国内要翻墙才能下pretrain model，可以提供百度云等途径吗？

### ISSUE THREAD

**Issue by foxet** [chenyuntc/simple-faster-rcnn-pytorch#29]
您好，国内要翻墙才能下pretrain model，我运算机器是远程的国内机器，无法翻墙，请问可以提供百度云等途径吗？

万分感谢

**Comment by chenyuntc** [comment]
是预训练的faster rcnn?
https://github.com/chenyuntc/simple-faster-rcnn-pytorch#4-demo  
这里有百度网盘的地址
