### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by Sun-Wu-kon** [chenyuntc/simple-faster-rcnn-pytorch#3]
when i run train.py after load data it occurs ConnectionError
like this:
 
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f014c50b438>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by yangshao** [comment]
@Sun-Wu-kon Hi, I also come across this problem, how do you solve it?

**Comment by xylcbd** [comment]
before you start training, please start the visdom server:
```
python -m visdom.server
```
