### ISSUE TITLE
torchnet

### ISSUE THREAD

**Issue by blakeliu** [chenyuntc/simple-faster-rcnn-pytorch#4]
How install torchnet into win10????

**Comment by chenyuntc** [comment]
I think it could be installed by
```bash
pip install git+https://github.com/pytorch/tnt.git@master
```
But I haven't tried it, since I don't have a windows-pc.

By the way, I don't recommend to run this code in windows. it may be buggy.

I'll close it for now, feel free to reopen it  if you have any questions.

**Comment by blakeliu** [comment]
Thanks，it work!

**Comment by blakeliu** [comment]
@chenyuntc  Thanks，it work!
