### ISSUE TITLE
nms_gpu_post安装出错

### ISSUE THREAD

**Issue by dongfengxijian** [chenyuntc/simple-faster-rcnn-pytorch#48]
phd@phd-HP-xw8600-Workstation:~/PycharmProjects/Examples/simple-faster-rcnn-pytorch/model/utils/nms$ python3 build.py build_ext --inplace
running build_ext
skipping '_nms_gpu_post.c' Cython extension (up-to-date)
building '_nms_gpu_post' extension
gcc -pthread -B /home/phd/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/phd/anaconda3/include/python3.6m -c _nms_gpu_post.c -o build/temp.linux-x86_64-3.6/_nms_gpu_post.o
_nms_gpu_post.c:525:31: fatal error: numpy/arrayobject.h: 没有那个文件或目录
compilation terminated.
error: command 'gcc' failed with exit status 1

我的python是用anaconda安装的，现在报这个错，但是numpy是有的

**Comment by joyliu37** [comment]
Hey, I also have this problem. It's because the numpy dir is not include in the setup. You could follow the solution in this [link:](https://stackoverflow.com/questions/14657375/cython-fatal-error-numpy-arrayobject-h-no-such-file-or-directory) . Hope this can help you.

**Comment by dongfengxijian** [comment]
Thank you!

**Comment by dongfengxijian** [comment]
Thank you！






------------------ 原始邮件 ------------------
发件人: "joyliu37"<notifications@github.com>;
发送时间: 2018年6月3日(星期天) 下午2:30
收件人: "chenyuntc/simple-faster-rcnn-pytorch"<simple-faster-rcnn-pytorch@noreply.github.com>;
抄送: "东风西渐"<860782934@qq.com>; "Manual"<manual@noreply.github.com>; 
主题: Re: [chenyuntc/simple-faster-rcnn-pytorch] nms_gpu_post安装出错 (#48)




Hey, I also have this problem. It's because the numpy dir is not include in the setup. You could follow the solution in this link: . Hope this can help you.
