### ISSUE TITLE
model/utils/creator_tool.py#L125

### ISSUE THREAD

**Issue by jiarenyf** [chenyuntc/simple-faster-rcnn-pytorch#5]
Thank you for your effort, and I wonder that should the `pos_roi_per_this_image` be `neg_roi_per_this_image` in [model/utils/creator_tool.py#L125](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/blob/cf1bb347d4b787aeffde9a72c508d65f127eba73/model/utils/creator_tool.py#L125) ?

**Comment by chenyuntc** [comment]
I'm afraid that you mixed them up, `gt_roi_label` looks like:
[pos,  pos,  pos, pos,  pos,   ...,    pos, neg, neg, neg...]
|--- pos_roi_per_this_image ---|

There  `pos_roi_per_this_image` items at the begining of `gt_roi_label`is positive, 
`gt_roi_label[pos_roi_per_this_image:]` means items after the `pos_roi_per_this_image`th.

**Comment by chenyuntc** [comment]
Feel free to reopen it if you have any questions.
