### ISSUE TITLE
How about filtering difficultes in Dataset instead?

### ISSUE THREAD

**Issue by acgtyrant** [chenyuntc/simple-faster-rcnn-pytorch#6]
In other words, only return labels and gt_bboxes which are not difficultes in Dataset, so we do not need to process difficultes in others places any more.

If you have tried it, I would like to know is it equivalent to processing difficultes in others places.

**Comment by acgtyrant** [comment]
I find you have filtered it in Dataset already, forget it.

**Comment by acgtyrant** [comment]
I read the code again, I find the difficultes is important in voc_eval to ignore those successful difficulte detection.

**Comment by chenyuntc** [comment]
yes you are right .
see [chainer/chainercv#297](https://github.com/chainer/chainercv/issues/297#issuecomment-311007050)
