### ISSUE TITLE
vgg16-397923af.pth download

### ISSUE THREAD

**Issue by shangjianan2** [chenyuntc/simple-faster-rcnn-pytorch#63]
链接：https://pan.baidu.com/s/1DFxRkVBRjbDBDKKXdND47A 密码：u0xf

**Comment by shangjianan2** [comment]
Sometimes we can not download vgg16-397923af.pth. Here is vgg16-397923af.pth I have already download. I hope it will useful to you.

**Comment by chenyuntc** [comment]
Thank you! I'll update it in README and close the issue here.

**Comment by Stephenfang51** [comment]
Dear Sir

Thanks for the Baidu Pan.

However, the "convert_caffe_pretrain.py" can't convert the "vgg16-397923af" into torch version. I tried and it failed.

The network has different structure between vgg16-397923a and vgg16-00b39a1b I guess

I suggest people can download the vgg16-00b39a1b.pth on Google Colab and covert to torch version using "convert_caffe_pretrain.py" as Chenyun said in README. 

Thanks !

**Comment by greenyin** [comment]
> Dear Sir
> 
> Thanks for the Baidu Pan.
> 
> However, the "convert_caffe_pretrain.py" can't convert the "vgg16-397923af" into torch version. I tried and it failed.
> 
> The network has different structure between vgg16-397923a and vgg16-00b39a1b I guess
> 
> I suggest people can download the vgg16-00b39a1b.pth on Google Colab and covert to torch version using "convert_caffe_pretrain.py" as Chenyun said in README.
> 
> Thanks !

I also encountered the same problem, did you solve it?

**Comment by shida666** [comment]
> > Dear Sir
> > Thanks for the Baidu Pan.
> > However, the "convert_caffe_pretrain.py" can't convert the "vgg16-397923af" into torch version. I tried and it failed.
> > The network has different structure between vgg16-397923a and vgg16-00b39a1b I guess
> > I suggest people can download the vgg16-00b39a1b.pth on Google Colab and covert to torch version using "convert_caffe_pretrain.py" as Chenyun said in README.
> > Thanks !
> 
> I also encountered the same problem, did you solve it?

NameError: name 'sd' is not defined      did you solve it?

**Comment by shida666** [comment]
Hey , everyone ! The file “vgg16-397923af.pth“ we downloaded is a pre-trained model that pre-trained in Pytroch environment ! it doesn't be pretrained in the Caffe ! so we download the vgg16-397923af.pth fire into "checkpoints" folder , and we dont need to make the "python misc/convert_caffe_pretrain.py"in our shell , and we should directly to the "python train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain“ ！

**Comment by shida666** [comment]
> > Dear Sir
> > Thanks for the Baidu Pan.
> > However, the "convert_caffe_pretrain.py" can't convert the "vgg16-397923af" into torch version. I tried and it failed.
> > The network has different structure between vgg16-397923a and vgg16-00b39a1b I guess
> > I suggest people can download the vgg16-00b39a1b.pth on Google Colab and covert to torch version using "convert_caffe_pretrain.py" as Chenyun said in README.
> > Thanks !
> 
> I also encountered the same problem, did you solve it?

directly to insert the "python train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain“  don't make the  ‘’python misc/convert_caffe_pretrain.py‘’

**Comment by shida666** [comment]
> Hey , everyone ! The file “vgg16-397923af.pth“ we downloaded is a pre-trained model that pre-trained in Pytroch environment ! it doesn't be pretrained in the Caffe ! so we download the vgg16-397923af.pth fire into "checkpoints" folder , and we dont need to make the "python misc/convert_caffe_pretrain.py"in our shell , and we should directly to the "python train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain“ ！

mv vgg16-397923af.pth vgg16_caffe.pth  don't forget to change the name of the file!

**Comment by ZichengDuan** [comment]
Hi, could anyone tell me that is it a must for me to use the pretrained model? Can I just start the training with ramdon numbers? Thanks.

**Comment by chenaifang** [comment]
I want to use vgg16_bn, but directly use vgg16_bn-6c64b313.pth in Pytorch.  I  can only get 58mAP. I would like to ask if there are other pre-training models of vgg16_bn? @shangjianan2 @chenyuntc @greenyin @ZichengDuan @Stephenfang51

**Comment by ZichengDuan** [comment]
@chenaifang Hi, Aifang. Unfortunately, I didn't explore other backbone networks for this project.

**Comment by chenaifang** [comment]
Excuse me, do you know how to get the pre-training model of vgg16_bn in general? @ZichengDuan

**Comment by yuanzhenhuan** [comment]
thank you对对对

**Comment by DanZhang123** [comment]
> I want to use vgg16_bn, but directly use vgg16_bn-6c64b313.pth in Pytorch. I can only get 58mAP. I would like to ask if there are other pre-training models of vgg16_bn? @shangjianan2 @chenyuntc @greenyin @ZichengDuan @Stephenfang51

Hello, have you solved it?
