### ISSUE TITLE
Error in python3 build.py build_ext --inplace 

### ISSUE THREAD

**Issue by jhk623** [chenyuntc/simple-faster-rcnn-pytorch#7]
if i do python3 build.py build_ext --inplace, there is an error like this

running build_ext
skipping '_nms_gpu_post.c' Cython extension (up-to-date)
building '_nms_gpu_post' extension
gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/include/python3.6m -c _nms_gpu_post.c -o build/temp.linux-x86_64-3.6/_nms_gpu_post.o
_nms_gpu_post.c:485:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include "numpy/arrayobject.h"
                               ^
compilation terminated.
error: command 'gcc' failed with exit status 1

im in nvidia-docker environment, cupy 2.2.0 cuda 8.0 python 3.6.3 and torch 0.3.0

i'll look for your help

thanks

**Comment by acgtyrant** [comment]
do you have installed numpy?

if not, pip install -r requirements.txt

**Comment by jhk623** [comment]
it is solved by reinstalling numpy with
pip uninstall numpy
apt-get install python3-numpy

**Comment by xingkongliang** [comment]
build.py
```
import numpy

ext_modules = [Extension("_nms_gpu_post", ["_nms_gpu_post.pyx"],
                  include_dirs=[numpy.get_include()])]
```

**Comment by xincxiong** [comment]
> add `import numpy` and `include_dirs` to build.py
> like:
> 
> ```
> import numpy
> 
> ext_modules = [Extension("_nms_gpu_post", ["_nms_gpu_post.pyx"],
>                   include_dirs=[numpy.get_include()])]
> ```

It really works. SOLVED!!

**Comment by GanAndreas** [comment]
> include_dirs=[numpy.get_include()])]

sweet Jesus!!!
